version: '3.4'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:latest
    networks:
     - k6
     - grafana
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/test.js --vus 20 --iterations 500



  k6_token:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6567:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/token.js --vus 20 --iterations 500

  k6_address:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6566:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/clientAddress.js --vus 20 --iterations 500      

  k6_clientKyc:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6568:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/clientKyc.js --vus 20 --iterations 500      

  k6_clientVerify:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6569:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/clientVerify.js --vus 20 --iterations 500  

  k6_card_activate:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6570:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/cardActivate.js --vus 20 --iterations 500    
    
  k6_card_register:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6571:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/cardRegister.js --vus 20 --iterations 500 


  k6_clientTbsRemain:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6572:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/clientTbsRemain.js --vus 20 --iterations 500  


  k6_clientBankRemains:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6573:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/clientBankRemains.js --vus 20 --iterations 500 

  k6_clientIsLegal:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6574:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/clientIsLegal.js --vus 20 --iterations 500 

   k6_paymentTbsToCard:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6575:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/paymentTbsToCard.js --vus 20 --iterations 500 
  k6_paymentCardToTbs:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6576:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../load_test/k6_tests:/scripts
    command: run  ./scripts/paymentCardToTbs.js --vus 20 --iterations 500 

#  test_server:
#    image: alpine:latest
#    networks:
#      - grafana
#    command:
#      - sh

  mofid_wallet:
    image: mofid_wallet
    networks:
      - k6
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=loadtest